
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: postgres
  password: 123
  port: 5432
  host: localhost

development:
  <<: *default
  database: books_dev
test:
  <<: *default
  database: books_test
production:
  <<: *default
  database: books_prod
  username: books
  password: <%= ENV['BOOKS_DATABASE_PASSWORD'] %>
